version: "1.0"
services:
  backend:
    build: . # Build image from local Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    ports:
      - "3000:3000" # Expose port 3000 on host
    depends_on:
      - db # Wait until database service is loaded
    networks:
      - app-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - app-network
networks: # Specify the network for bridging
  app-network:
    driver: bridge
